### ISSUE TITLE
ES Module Syntax Support

### ISSUE THREAD

**Issue by muuvmuuv** [hughsk/flat#101]
Would be great if flat can be imported as ES modules. 

Ref: https://github.com/ngneat/transloco/issues/301

**Comment by jonkoops** [comment]
This has been fixed by #149.

**Comment by seravifer** [comment]
Thanks @jonkoops! Do you know when it will be released?

**Comment by jonkoops** [comment]
@seravifer I do not have permission to publish, but I have asked @hughsk to do a release (see #156).

**Comment by dmytro-afonin** [comment]
When is it going to be released? My app is failing when I am updating to v5

**Comment by jonkoops** [comment]
This has already been released [under v6](https://github.com/hughsk/flat/releases/tag/v6.0.0).
