### ISSUE TITLE
There is no 4.1.1 on npm

### ISSUE THREAD

**Issue by xPaw** [hughsk/flat#110]
`warning mocha > yargs-unparser > flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.`

But there is no 4.1.1 to update to. https://www.npmjs.com/package/flat/v/4.1.1

**Comment by DevRCRun** [comment]
Same is true of 4.1.2

**Comment by waldemarnt** [comment]
same here, any news?

**Comment by Hypnosphi** [comment]
@timoxley can you please comment on that?

**Comment by timoxley** [comment]
Fixed. 4.1.1 published.

> Same is true of 4.1.2
There was never a 4.1.2.

**Comment by AviVahl** [comment]
@timoxley `latest` now points to 3.0.1 instead of 5.0.2 :o

**Comment by timoxley** [comment]
Ugh I thought npm fixed that so it wouldn't update the latest tag to an older version

**Comment by timoxley** [comment]
Will fix,

**Comment by timoxley** [comment]
Fixed
