### ISSUE TITLE
Should provide ES5 syntax build.

### ISSUE THREAD

**Issue by rockmandash** [hughsk/flat#111]
There are lots of build tools that still don't support modern build.

![image](https://user-images.githubusercontent.com/7580792/90857790-759d8800-e3b7-11ea-8d61-dc0d4f086644.png)

**Comment by jonkoops** [comment]
There is no intention to revert back to older ECMAScript syntax. I recommend that you update your tooling instead, and optionally transpile your code if you need to support older runtimes.
