### ISSUE TITLE
High severity vulnerability detected

### ISSUE THREAD

**Issue by kamalyzl** [hughsk/flat#117]
A security assessment was performed and vulnerabilities

Standards and Best Practices

    OWASP 2017
        A9 - Using Components with Known Vulnerabilities
    PCI 3.2
        6.2 - Known Vulnerabilities

Please, help!

**Comment by cynsupercat** [comment]
Hi guys,

We also have the same issue -- [prototype pollution](https://www.sourceclear.com/vulnerability-database/security/prototype-pollution/javascript/sid-27574). Wonder if there would be any ETA to this?

**Comment by JoshMerlino** [comment]
PwnFunction just made a great video explaining this vulnerability. Here it is for those who are interested. https://youtu.be/XS_UMqQalLI
