### ISSUE TITLE
High security vulnerability in 4.1.1

### ISSUE THREAD

**Issue by anujkaushal** [hughsk/flat#125]
[4.1.1](https://github.com/hughsk/flat/tree/4.1.1) have high security vulnerability which is being used by latest version of [Theia](https://github.com/eclipse-theia/theia) in a deep dependency 
Theia package [electron-mocha](https://github.com/eclipse-theia/theia/blob/master/yarn.lock#L4066-L4067) is using flat in a deep dependency, see the tree below.
![image](https://user-images.githubusercontent.com/32764738/120937699-8b085680-c72c-11eb-96d4-bf96d09b8996.png)
```
{
  "severity": "High",
  "type": "security",
  "summary": "flat Package for Node.js index.js unflatten() Function Object Prototype Manipulation Unspecified Issue",
  "description": "flat Package for Node.js contains a flaw in the unflatten() function in index.js that is triggered as access to object prototypes is improperly handled. This may allow a context-dependent to manipulate object properties and have an unspecified impact.",
  "impacted_artifacts": [{
    "depth": 0,
    "infected_files": [{
      "name": "package.json",
      "path": "theia-app/node_modules/flat/",
      "depth": 0,
      "pkg_type": "Npm",
      "display_name": "flat:4.1.1"
    }]
  }]
}
```

It would be much appreciated if you can fix this vulnerability in the next 4.1.x version.

**Comment by jonkoops** [comment]
Closing this issue as this has been resolved.
