### ISSUE TITLE
Make the function extensible with custom logic - `plugin` / `middleware` / `process callback`

### ISSUE THREAD

**Issue by softmarshmallow** [hughsk/flat#178]
I am working on a no-code builder, and I am using `flat` to build a output json.

I want to extend its feature to handle nested array as flat, e.g.

```
{
   "**0": [1],
   "**1": [2, 3],
   "**2": [4],   
}
```

will output
```
[1, 2, 3, 4]
```

There is no clean way to handle this, and the packages' extensibility is somewhat limited.

Any plans on having custom callback or plugin feature?

**Comment by jonkoops** [comment]
No, there are not plans for a function to allow extending the library in this way. If you need this kind of functionality I would recommend either preprocessing your data, or to write your own custom implementation entirely.
