### ISSUE TITLE
Unflatten not happening properly

### ISSUE THREAD

**Issue by user1702** [hughsk/flat#26]
I have tried the below code, where "c.d": 20 turns into "c: { d: 20 }". I have used {object:true} which also didnt help me.

var flatten = require('flat'),
    unflatten = require('flat').unflatten;

var obj1 = flatten({a: 10, b: 15, "c.d": 20, e: 50})

var res = flatten(obj1)
console.log(res) //{ a: 10, b: 15, 'c.d': 20, e: 50 }
var fin = unflatten(res,{object: true});
console.log(fin) //{ a: 10, b: 15, c: { d: 20 }, e: 50 }

**Comment by timoxley** [comment]
Try changing the delimiter:
```js
unflatten({a: 10, b: 15, "c.d": 20, e: 50}, {delimiter: '|'});
```

**Comment by user1702** [comment]
Thanks timoxley. It worked for the above object but not working for my below actual object.

Below is the flattened object which I am trying to unflatten.
var obj = {'Query_obj._id': 1,
  'data_to_update.$inc.stock': 5999,
  'data_to_update.$set.item': 'ABC123',
  'data_to_update.$set.info.publisher': '2222',
  'data_to_update.$set.tags.0': 'software',
  'data_to_update.$set.ratings.1.by': 'xyz',
  'data_to_update.$set.ratings.1.rating': 3 }

unflatten(obj); 
//{"Query_obj":{"_id":1},"data_to_update":{"$inc":{"stock":5999},"$set":{"item":"ABC123","info":{"publisher":"2222"},"tags":["software"],"ratings":[null,{"by":"xyz","rating":3}]}}}

unflatten(obj,{delimiter: '|'});
//{"Query_obj._id":1,"data_to_update.$inc.stock":5999,"data_to_update.$set.item":"ABC123","data_to_update.$set.info.publisher":"2222","data_to_update.$set.tags.0":"software","data_to_update.$set.ratings.1.by":"xyz","data_to_update.$set.ratings.1.rating":3}


I am expecting the output to be as below (maintaing the key name as it is like info.publisher)

//{"Query_obj":{"_id":1},"data_to_update":{"$inc":{"stock":5999},"$set":{"item":"ABC123","info.publisher":"2222","tags":["software"],"ratings.1":{"by":"xyz","rating":3}}}}

**Comment by timoxley** [comment]
@user1702 I don't think that's possible at the moment, how would it decide when `.` means "keep in key" and when it means "new level"?

**Comment by timoxley** [comment]
Closing as abandoned. Please reopen if you have further queries.
