### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by abhinav76** [hughsk/flat#32]
i tried to use flatten on the data retrieved from the database
but recieved this error
<code>
Unhandled rejection RangeError: Maximum call stack size exceeded
    at new Boolean (native)
    at Boolean.toString (native)
    at /opt/lampp/htdocs/node-fropper/node_modules/flat/index.js:17:44
    at Array.forEach (native)
    at step (/opt/lampp/htdocs/node-fropper/node_modules/flat/index.js:14:25)
    at /opt/lampp/htdocs/node-fropper/node_modules/flat/index.js:34:16
    at Array.forEach (native)
    at step (/opt/lampp/htdocs/node-fropper/node_modules/flat/index.js:14:25)
    at /opt/lampp/htdocs/node-fropper/node_modules/flat/index.js:34:16
    at Array.forEach (native)
    at step (/opt/lampp/htdocs/node-fropper/node_modules/flat/index.js:14:25)
    at /opt/lampp/htdocs/node-fropper/node_modules/flat/index.js:34:16
    at Array.forEach (native)
    at step (/opt/lampp/htdocs/node-fropper/node_modules/flat/index.js:14:25)
    at /opt/lampp/htdocs/node-fropper/node_modules/flat/index.js:34:16
    at Array.forEach (native)

</code>
full error looks like this

**Comment by kulicuu** [comment]
you'll want a `process.nextTick()` somewhere in there.

**Comment by abhinav76** [comment]
<code>
var member=Member.build();
	member.retrieveProfile(username).spread(function(members,error){
		if(members){
			flatten(members);
			res.json(members);
		} else{
			res.send(401,"No Profile Found");
		}
	},function(error){
		res.send(error);
	});
</code>
here is my code

**Comment by kulicuu** [comment]
I'm sorry, based on that I can't tell and haven't the time for a real inquiry.  I still think you are going to need to insert `process.nextTick()` somewhere.  Best I can offer for now, sorry.

**Comment by stockholmux** [comment]
@abhinav76 Can you `console.log` your `members` variable before you call `flatten`?

**Comment by abhinav76** [comment]
yes it gives me all the data @stockholmux 
and res.json give me the data like this:
<code>
{
f_name="",
profile={
    "member_username"="",
    "some other field "=""
}

}
</code>

**Comment by stockholmux** [comment]
@abhinav76 what you've provided isn't a JS object and that doesn't look like the real output of a `console.log`. You can redact user info if you need to, but seeing the actual result of the log will help us understand why you're getting the error and maybe help you out.

My hunch is there is a circular reference somewhere in your object. This is the only way I could get a `RangeError: Maximum call stack size exceeded` error:

```
var
  flatten = require('flat'),
  a = {},
  b = {};

a.info = b;
b.info = a;

console.log(flatten(a));
```

**Comment by abhinav76** [comment]
hey this my console output @stockholmux 
<code>
{ dataValues: 
   { f_name: '',
     profile: 
      { dataValues: [Object],
        _previousDataValues: [Object],
        _changed: {},
        __options: [Object],
        options: [Object],
        hasPrimaryKeys: true,
        __eagerlyLoadedAssociations: [],
        isNewRecord: false,
        profile_personality: [Object] } },
  _previousDataValues: 
   { f_name: '',
     profile: 
      { dataValues: [Object],
        _previousDataValues: [Object],
        _changed: {},
        __options: [Object],
        options: [Object],
        hasPrimaryKeys: true,
        __eagerlyLoadedAssociations: [],
        isNewRecord: false,
        profile_personality: [Object] } },
  _changed: {},
  __options: 
   { timestamps: false,
     instanceMethods: 
      { retrieveAll: [Function],
        signinByEmail: [Function],
        findId: [Function],
        retrieveProfile: [Function],
        updateMember: [Function],
        addMember: [Function] },
     classMethods: {},
     validate: {},
     freezeTableName: true,
     underscored: false,
     underscoredAll: false,
     paranoid: false,
     whereCollection: { username: 'nikhil271' },
     schema: null,
     schemaDelimiter: '',
     defaultScope: null,
     scopes: null,
     hooks: {},
     indexes: [],
     name: { plural: 'members', singular: 'member' },
     tableName: 'member',
     omitNull: false,
     sequelize: 
      { options: [Object],
        config: [Object],
        dialect: [Object],
        models: [Object],
        modelManager: [Object],
        connectionManager: [Object],
        importCache: {},
        test: [Object],
        queryInterface: [Object] },
     uniqueKeys: {},
     hasPrimaryKeys: true },
  options: 
   { isNewRecord: false,
     include: [ [Object] ],
     includeNames: [ 'profile' ],
     includeMap: { profile: [Object] },
     includeValidated: true,
     attributes: [ 'f_name' ],
     raw: true },
  hasPrimaryKeys: true,
  __eagerlyLoadedAssociations: [],
  isNewRecord: false,
  profile: 
   { dataValues: 
      { member_username: 'nikhil271',
        member_gender: 'Male',
        member_dob: 0,
        member_country: '',
        state: '',
        city: '',
        hair_colour: '',
        hairstyle: '',
        eye_colour: '',
        eyesight: '',
        complexion: '',
        height: '',
        body_ENGINE: '',
        exercise: '',
        religion: '',
        religious_beliefs: '',
        education: '',
        occupation: '',
        annual_income: '',
        ethnicity: '',
        nationality: '',
        languages: '',
        diet: '',
        smoke: '',
        drink: '',
        current_relationship_status: '',
        preferred_relationship: '',
        profile_tagline: '',
        screened: 'N',
        photo_status: 'None',
        hidden: 'N',
        record_date: 0,
        update_date: 0,
        ip: '',
        member_id: 10448,
        time_stamp: 0,
        photo_key: '',
        profile_personality: [Object] },
     _previousDataValues: 
      { member_username: 'nikhil271',
        member_gender: 'Male',
        member_dob: 0,
        member_country: '',
        state: '',
        city: '',
        hair_colour: '',
        hairstyle: '',
        eye_colour: '',
        eyesight: '',
        complexion: '',
        height: '',
        body_ENGINE: '',
        exercise: '',
        religion: '',
        religious_beliefs: '',
        education: '',
        occupation: '',
        annual_income: '',
        ethnicity: '',
        nationality: '',
        languages: '',
        diet: '',
        smoke: '',
        drink: '',
        current_relationship_status: '',
        preferred_relationship: '',
        profile_tagline: '',
        screened: 'N',
        photo_status: 'None',
        hidden: 'N',
        record_date: 0,
        update_date: 0,
        ip: '',
        member_id: 10448,
        time_stamp: 0,
        photo_key: '',
        profile_personality: [Object] },
     _changed: {},
     __options: 
      { timestamps: false,
        instanceMethods: [Object],
        classMethods: {},
        validate: {},
        freezeTableName: true,
        underscored: false,
        underscoredAll: false,
        paranoid: false,
        whereCollection: null,
        schema: null,
        schemaDelimiter: '',
        defaultScope: null,
        scopes: null,
        hooks: {},
        indexes: [],
        name: [Object],
        tableName: 'profile',
        omitNull: false,
        sequelize: [Object],
        uniqueKeys: {},
        hasPrimaryKeys: true },
     options: 
      { isNewRecord: false,
        include: [Object],
        includeNames: [Object],
        includeMap: [Object],
        includeValidated: true,
        raw: true,
        attributes: undefined },
     hasPrimaryKeys: true,
     __eagerlyLoadedAssociations: [],
     isNewRecord: false,
     profile_personality: 
      { dataValues: [Object],
        _previousDataValues: [Object],
        _changed: {},
        __options: [Object],
        options: [Object],
        hasPrimaryKeys: true,
        __eagerlyLoadedAssociations: [],
        isNewRecord: false,
        profile_other_info: [Object] } } }


</code>

**Comment by stockholmux** [comment]
Okay. Now it's starting to make sense. Looks like you've got quite a bit more than just data in that structure - it has functions, needlessly deep references and most likely circular references. You'll need to to quite a bit of cleanup on your data before you `flat` it. I haven't used sequelize in years, but I'm guessing there is a way to get just the data from that giant structure - a good deal of it looks like it is for sequelize internal use only. Best of luck.

**Comment by timoxley** [comment]
@abhinav76 Going to close this, please reopen if you think flat could help out more. 

@stockholmux thanks for helping!
