### ISSUE TITLE
unflatten depends on "key" order

### ISSUE THREAD

**Issue by lipp** [hughsk/flat#43]
this is a bit surprising to me, but apperently the order in which object entries are created affect the output of `unflatten`
see here:
https://tonicdev.com/lipp/flat-issue

a solution seems to be to itereate through the object keys sorted by length.

**Comment by flight9** [comment]
I don't think sorted by length is always a good idea. Is there a way to close this feature and use original order?

**Comment by lenchvolodymyr** [comment]
Sorting keys breaks an order:

f = require('flat');
console.log(
	Object.keys(
		f.unflatten(
			f.flatten({
				a: 1,
				abcdefg: 1,
				d: 1
			})
		)
	)
);

expected [ 'a', 'abcdefg', 'd' ], but appears [ 'a', 'd', 'abcdefg' ]
