### ISSUE TITLE
maxDepth only working on first element

### ISSUE THREAD

**Issue by nickpape** [hughsk/flat#48]
Hey everyone,

It appears that when using maxDepth, only the first key value is being properly flattened. You can easily see this behaviour if you update the `customDepth` test to:

``` javascript
flatten({
  hello: {
    world: {
      again: 'good morning'
    }
  },
  lorem: {
    ipsum: {
      dolor: 'good evening'
    }
  }
}, {
  maxDepth: 2
})
```

Instead of the expected result:

``` javascript
{
  'hello.world': {
    again: 'good morning'
  },
  'lorem.ipsum': {
    dolor: 'good evening'
  }
}
```

You instead receive:

``` javascript
{
  'hello.world': { 
    again: 'good morning'
  },
  lorem: {
    ipsum: {
      dolor: 'good evening'
    }
  }
}
```

The issue appears to be that the `currentDepth` variable is only incremented, and never reset or decremented.

I have created a pull request #47 to remedy the situation.

**Comment by Darkilen** [comment]
This issue should be closed. She was resolved more than 2 years ago. (#47)

**Comment by jonkoops** [comment]
Closing for reasons mentioned above.
