### ISSUE TITLE
When a property name is a number, it is truncated after unflatten

### ISSUE THREAD

**Issue by Stijnkool** [hughsk/flat#50]
When I have an object like `{'a.b.0001': 'test'}` after unflatten it becomes `{a: {b: {1: 'test'}}}`.
And it should be `{a: {b: {'0001': 'test'}}}`
I believe this to be bug.

**Comment by evseevnn** [comment]
same problem

**Comment by deividfortuna** [comment]
Solved on pull request #57

**Comment by jonkoops** [comment]
Closing this for reasons mentioned above.
