### ISSUE TITLE
Major rewrite in progress

### ISSUE THREAD

**Issue by kristianmandrup** [hughsk/flat#51]
I'm doing a major rewrite using ES6 on this [flat#dev](https://github.com/kristianmandrup/flat/tree/dev) branch

The current implementation was getting out of hand and full of "garbage" to make it very difficult to make sense of. Let me know if you want to help out in this effort.
I'm planning to use `flat` in my [json-operator](https://github.com/kristianmandrup/json-operator)

**Comment by kristianmandrup** [comment]
I've been trying to compose the functionality into more granular functions, classes and encapsulated state. When it works, I would like to play with the ability to divide and conquer, ie. to process the flatten/unflatten via async tasks that are merged into the result.
Would love if someone would like to help out on this. Cheers!

**Comment by maximilianschmitt** [comment]
This is great!

**Comment by antony** [comment]
I've broken apart the flatten method as part of https://github.com/hughsk/flat/pull/61

I think it is worth moving some of these nested functions into separate files

**Comment by jonkoops** [comment]
Closing this issue as it is too abstract to really put some tasks on it. We have since re-written the source to use modern ECMAScript syntax (including modules).

Feel free to open up any PRs you think can improve the code.
