### ISSUE TITLE
Permission to use in an MIT licensed project

### ISSUE THREAD

**Issue by bugs181** [hughsk/flat#73]
I'd like to have your formal consent to add this dependency to a project which is licensed under the MIT license.

Project:
[expressive-middleware](https://github.com/bugs181/expressive-middleware)

License:
[MIT License](https://github.com/bugs181/expressive-middleware/blob/master/LICENSE)

**Comment by jonkoops** [comment]
There is no intention to dual license this package or to convert the license. The [BSD-3-Clause license](https://github.com/hughsk/flat/blob/master/LICENSE) is more than free enough for what you intend to do.
