### ISSUE TITLE
Arrow function breaks in IE.

### ISSUE THREAD

**Issue by bkbartonDesign** [hughsk/flat#95]
A single arrow function is breaking functionality in < IE11.

`target = Object.keys(target).reduce((result, key) =>`

I am using this module in the browser for a angular/typescript app.

**Comment by jackwlee01** [comment]
You need to a polyfill for Object.keys for IE11.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys#Polyfill

**Comment by ftes** [comment]
IE11 supports `Object.keys`. https://caniuse.com/#feat=es5

The issue, as stated in @bkbartonDesign 's description, is the arrow function.

**Comment by fedevitch** [comment]
Got the same issue, had to downgrade to 4.1.0 for resolving this. 
If you guys approve pr with fix for this https://github.com/hughsk/flat/pull/92 that would be great

**Comment by jonkoops** [comment]
We no longer provide support for Internet Explorer, and neither does Microsoft at this point.
