### ISSUE TITLE
Feature request: Flatten __proto__

### ISSUE THREAD

**Issue by Ghost---Shadow** [hughsk/flat#98]
```js
const a = {
  __proto__: {
    fun: () => 'foo',
    __proto__: {
      fun: () => 'bar',
    },
  },
};
```

Should flatten to

```js
const a = {
  '__proto__.fun': () => 'foo',
  '__proto__.__proto__.fun': () => 'bar',
};
```

We can have a flag like `extraKeys: ['__proto__']`

**Comment by kapouer** [comment]
A very good way to [shoot yourself in the foot](https://blog.p6.is/Real-World-JS-1/)

**Comment by Ghost---Shadow** [comment]
@kapouer 
![Screenshot 2022-03-22 082624](https://user-images.githubusercontent.com/7743925/159429103-b178d9c4-2888-426e-95a0-76d21b31a9c6.png)

**Comment by jonkoops** [comment]
I don't see a good reason to implement this, these are reserved parts of an object and should not be considered serializable. For example `JSON.stringify()` also ignores these values.
